### PR TITLE
Populate+improve options

### PR DESCRIPTION
**Pull request by Kyr**
## Explanation:
Given we have `model::sails.model` that, for some reason, have lifecycle callback:
```javascript
beforeDestroy: function(condition, next){
  next(new Error(403, 'Delete forbidden'));
}
```
When trying to populate fixtures into `Model` throws exception.
## Solution:
Give ability to preserve exists data via passing parameter to `.populate`. Aside: wrap passed options to object, with backward capability.

> I'm so sorry about 'spaces'.

### CODE REVIEW

**Comment by ybrodsky** [comment]
I am having the problem described by @Kyr . This is needed.

**Comment by bredikhin** [comment]
I really can't estimate / review the changes without the original two-space coding style kept. Please convert your code to the original repository style and rebase your commits with the current master. Thanks!

**Comment by Kyr** [comment]
My apologies @bredikhin , I'm restore original code-style.
Maybe adding .editorconfig could avoid such confusing?

**Comment by bredikhin** [comment]
Sorry, I still see some tabs in the code. Also, the PR can't be merged because of some conflicts, and the code itself needs more work. Please, resolve the conflicts and open a new PR against the branch called `feature/options`.

**Pull request closed without merging**
